version: "3.7"

services:

# backend laravel
  php:
    build:
      context: ./docker/laravel/php
      dockerfile: Dockerfile
    container_name: ${DOCKER_APP}-php
    volumes:
      - ./todo-app:/var/www/html
    expose:
      - 9000
    ports:
      - "9000:9000"
    links:
      - mysql
    networks:
      - app-network
    
  # nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: ${DOCKER_APP}-nginx
    expose:
      - "80"
    ports:
      - "8080:80"
    volumes:
      - ./todo-app:/var/www/html
      - ./docker/laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  # mysl Service
  mysql:
    image: mysql:8.0.27
    container_name: ${DOCKER_APP}-mysql
    restart: unless-stopped
    tty: true
    expose:
      - "3306"
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      # MYSQL_USER: ${DB_USERNAME} - not to be used for "root"
      # MYSQL_PASSWORD: ${DB_PASSWORD} - use mysql_root_password for root user's password
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${DOCKER_APP}-phpmyadmin
    restart: always
    expose:
      - "80"
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge